name: Tests

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.9", "3.10", "3.11"]
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install -r requirements-sentry.txt
        pip install pytest pytest-cov
    - name: Run pytest
      run: |
        pytest --cov=app tests/ --junitxml=test-results_${{ matrix.python-version }}.xml
    - name: Upload Test Results
      uses: actions/upload-artifact@v4
      with:
        name: test-results_${{ matrix.python-version }}.xml
        path: test-results_${{ matrix.python-version }}.xml
    - name: Upload Coverage Report
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: coverage-${{ matrix.python-version }}
        path: .coverage
